version: '3'
services:
  nginx:
    image: nginx:stable-alpine

    volumes:
      # - ./nginx/default.conf:/etc/nginx/config.d/default.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  node-app:
    build: .
    # ports:
    #   - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    depends_on:
      - mongo
  
  mongo:
    image: mongo:5.0.9
    # ports:
    #   - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sachin
      - MONGO_INITDB_ROOT_PASSWORD=q
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:6.2.6
    
volumes:
  mongo-db: